language: python
# Enable Travis container-based infrastructure
sudo: false
python:
  - "3.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - pip install -r requirements.txt
 - python setup.py install # install package from sources
script:
 - ./Tests/testError.py
 - ./Tests/test_fslViewer.py
 