language: python
# Enable Travis container-based infrastructure
sudo: false
python:
  - "3.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - ls /home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/
 - pip install -r requirements.txt
 - python setup.py install # install package from sources
 # Install FSL using neurodebian
 - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
 - sudo apt-get -y update
 - sudo apt-get -y install fsl-complete
 - source /etc/fsl/fsl.sh;
 - export FSLOUTPUTTYPE=NIFTI_GZ
 - cwd=`pwd`
script:
 - ./nidmviewerfsl/tests/testError.py
 - ./nidmviewerfsl/tests/test_fslViewer.py
